import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";
import "~/app/globals.css";

const inter = Roboto({ weight: "400", subsets: ["latin"], display: "swap" });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className="min-vh-100">{children}</body>
        </html>
    );
}
