import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "~/app/globals.scss";
import StoreProvider from "~/store/StoreProvider";
import { Stack } from "@mui/material";

const inter = Roboto({ weight: "400", subsets: ["latin"], display: "swap" });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <StoreProvider>
            <html lang="en">
                <body>
                    {children}
                    <ToastContainer autoClose={2500} />
                </body>
            </html>
        </StoreProvider>
    );
}
